// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.34.1
// source: internal/control/control.proto

// Package fleetedr.control.v1 is the wire contract for the persistent agent
// control channel: a single bidirectional stream that pushes commands to a
// connected host in real time and carries command outcomes back. It is the
// push replacement for the GET /api/commands short-poll (issue #477). The
// channel authenticates once at connect via the host bearer token in
// connection metadata; there is no per-frame credential.

package control

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// ServerFrame is one message pushed from the gateway down to the agent. It is
// a oneof so the channel can carry future control kinds (interactive response
// session frames) without a second transport.
type ServerFrame struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Frame:
	//
	//	*ServerFrame_Command
	Frame         isServerFrame_Frame `protobuf_oneof:"frame"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ServerFrame) Reset() {
	*x = ServerFrame{}
	mi := &file_internal_control_control_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ServerFrame) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ServerFrame) ProtoMessage() {}

func (x *ServerFrame) ProtoReflect() protoreflect.Message {
	mi := &file_internal_control_control_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ServerFrame.ProtoReflect.Descriptor instead.
func (*ServerFrame) Descriptor() ([]byte, []int) {
	return file_internal_control_control_proto_rawDescGZIP(), []int{0}
}

func (x *ServerFrame) GetFrame() isServerFrame_Frame {
	if x != nil {
		return x.Frame
	}
	return nil
}

func (x *ServerFrame) GetCommand() *Command {
	if x != nil {
		if x, ok := x.Frame.(*ServerFrame_Command); ok {
			return x.Command
		}
	}
	return nil
}

type isServerFrame_Frame interface {
	isServerFrame_Frame()
}

type ServerFrame_Command struct {
	Command *Command `protobuf:"bytes,1,opt,name=command,proto3,oneof"`
}

func (*ServerFrame_Command) isServerFrame_Frame() {}

// AgentFrame is one message sent from the agent up to the gateway. Today the
// agent only reports command outcomes; the oneof leaves room for future kinds.
type AgentFrame struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Frame:
	//
	//	*AgentFrame_Outcome
	Frame         isAgentFrame_Frame `protobuf_oneof:"frame"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AgentFrame) Reset() {
	*x = AgentFrame{}
	mi := &file_internal_control_control_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AgentFrame) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AgentFrame) ProtoMessage() {}

func (x *AgentFrame) ProtoReflect() protoreflect.Message {
	mi := &file_internal_control_control_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AgentFrame.ProtoReflect.Descriptor instead.
func (*AgentFrame) Descriptor() ([]byte, []int) {
	return file_internal_control_control_proto_rawDescGZIP(), []int{1}
}

func (x *AgentFrame) GetFrame() isAgentFrame_Frame {
	if x != nil {
		return x.Frame
	}
	return nil
}

func (x *AgentFrame) GetOutcome() *Outcome {
	if x != nil {
		if x, ok := x.Frame.(*AgentFrame_Outcome); ok {
			return x.Outcome
		}
	}
	return nil
}

type isAgentFrame_Frame interface {
	isAgentFrame_Frame()
}

type AgentFrame_Outcome struct {
	Outcome *Outcome `protobuf:"bytes,1,opt,name=outcome,proto3,oneof"`
}

func (*AgentFrame_Outcome) isAgentFrame_Frame() {}

// Command mirrors the server-side command row the agent must execute. The
// field shapes match the JSON the poll path delivers so the wire shape is
// stable across both transports.
type Command struct {
	state       protoimpl.MessageState `protogen:"open.v1"`
	Id          int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	HostId      string                 `protobuf:"bytes,2,opt,name=host_id,json=hostId,proto3" json:"host_id,omitempty"`
	CommandType string                 `protobuf:"bytes,3,opt,name=command_type,json=commandType,proto3" json:"command_type,omitempty"`
	// payload is the raw command-type-specific JSON, forwarded verbatim (the
	// commander validates and the extension parses the same bytes).
	Payload       []byte `protobuf:"bytes,4,opt,name=payload,proto3" json:"payload,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Command) Reset() {
	*x = Command{}
	mi := &file_internal_control_control_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Command) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Command) ProtoMessage() {}

func (x *Command) ProtoReflect() protoreflect.Message {
	mi := &file_internal_control_control_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Command.ProtoReflect.Descriptor instead.
func (*Command) Descriptor() ([]byte, []int) {
	return file_internal_control_control_proto_rawDescGZIP(), []int{2}
}

func (x *Command) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *Command) GetHostId() string {
	if x != nil {
		return x.HostId
	}
	return ""
}

func (x *Command) GetCommandType() string {
	if x != nil {
		return x.CommandType
	}
	return ""
}

func (x *Command) GetPayload() []byte {
	if x != nil {
		return x.Payload
	}
	return nil
}

// Outcome is the agent's report for a command: the new status (acked,
// completed, or failed) and an optional result/error JSON blob. It maps onto
// the same UpdateStatus lifecycle the PUT /api/commands/{id} path uses.
type Outcome struct {
	state  protoimpl.MessageState `protogen:"open.v1"`
	Id     int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Status string                 `protobuf:"bytes,2,opt,name=status,proto3" json:"status,omitempty"`
	// result is the raw JSON result on completed, or an error blob on failed;
	// empty on acked.
	Result        []byte `protobuf:"bytes,3,opt,name=result,proto3" json:"result,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Outcome) Reset() {
	*x = Outcome{}
	mi := &file_internal_control_control_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Outcome) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Outcome) ProtoMessage() {}

func (x *Outcome) ProtoReflect() protoreflect.Message {
	mi := &file_internal_control_control_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Outcome.ProtoReflect.Descriptor instead.
func (*Outcome) Descriptor() ([]byte, []int) {
	return file_internal_control_control_proto_rawDescGZIP(), []int{3}
}

func (x *Outcome) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *Outcome) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *Outcome) GetResult() []byte {
	if x != nil {
		return x.Result
	}
	return nil
}

var File_internal_control_control_proto protoreflect.FileDescriptor

const file_internal_control_control_proto_rawDesc = "" +
	"\n" +
	"\x1einternal/control/control.proto\x12\x13fleetedr.control.v1\"P\n" +
	"\vServerFrame\x128\n" +
	"\acommand\x18\x01 \x01(\v2\x1c.fleetedr.control.v1.CommandH\x00R\acommandB\a\n" +
	"\x05frame\"O\n" +
	"\n" +
	"AgentFrame\x128\n" +
	"\aoutcome\x18\x01 \x01(\v2\x1c.fleetedr.control.v1.OutcomeH\x00R\aoutcomeB\a\n" +
	"\x05frame\"o\n" +
	"\aCommand\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x17\n" +
	"\ahost_id\x18\x02 \x01(\tR\x06hostId\x12!\n" +
	"\fcommand_type\x18\x03 \x01(\tR\vcommandType\x12\x18\n" +
	"\apayload\x18\x04 \x01(\fR\apayload\"I\n" +
	"\aOutcome\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x16\n" +
	"\x06status\x18\x02 \x01(\tR\x06status\x12\x16\n" +
	"\x06result\x18\x03 \x01(\fR\x06result2b\n" +
	"\x0eControlChannel\x12P\n" +
	"\aConnect\x12\x1f.fleetedr.control.v1.AgentFrame\x1a .fleetedr.control.v1.ServerFrame(\x010\x01B1Z/github.com/fleetdm/edr/internal/control;controlb\x06proto3"

var (
	file_internal_control_control_proto_rawDescOnce sync.Once
	file_internal_control_control_proto_rawDescData []byte
)

func file_internal_control_control_proto_rawDescGZIP() []byte {
	file_internal_control_control_proto_rawDescOnce.Do(func() {
		file_internal_control_control_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_internal_control_control_proto_rawDesc), len(file_internal_control_control_proto_rawDesc)))
	})
	return file_internal_control_control_proto_rawDescData
}

var file_internal_control_control_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_internal_control_control_proto_goTypes = []any{
	(*ServerFrame)(nil), // 0: fleetedr.control.v1.ServerFrame
	(*AgentFrame)(nil),  // 1: fleetedr.control.v1.AgentFrame
	(*Command)(nil),     // 2: fleetedr.control.v1.Command
	(*Outcome)(nil),     // 3: fleetedr.control.v1.Outcome
}
var file_internal_control_control_proto_depIdxs = []int32{
	2, // 0: fleetedr.control.v1.ServerFrame.command:type_name -> fleetedr.control.v1.Command
	3, // 1: fleetedr.control.v1.AgentFrame.outcome:type_name -> fleetedr.control.v1.Outcome
	1, // 2: fleetedr.control.v1.ControlChannel.Connect:input_type -> fleetedr.control.v1.AgentFrame
	0, // 3: fleetedr.control.v1.ControlChannel.Connect:output_type -> fleetedr.control.v1.ServerFrame
	3, // [3:4] is the sub-list for method output_type
	2, // [2:3] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_internal_control_control_proto_init() }
func file_internal_control_control_proto_init() {
	if File_internal_control_control_proto != nil {
		return
	}
	file_internal_control_control_proto_msgTypes[0].OneofWrappers = []any{
		(*ServerFrame_Command)(nil),
	}
	file_internal_control_control_proto_msgTypes[1].OneofWrappers = []any{
		(*AgentFrame_Outcome)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_internal_control_control_proto_rawDesc), len(file_internal_control_control_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_internal_control_control_proto_goTypes,
		DependencyIndexes: file_internal_control_control_proto_depIdxs,
		MessageInfos:      file_internal_control_control_proto_msgTypes,
	}.Build()
	File_internal_control_control_proto = out.File
	file_internal_control_control_proto_goTypes = nil
	file_internal_control_control_proto_depIdxs = nil
}
