// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v7.34.1
// source: internal/control/control.proto

// Package fleetedr.control.v1 is the wire contract for the persistent agent
// control channel: a single bidirectional stream that pushes commands to a
// connected host in real time and carries command outcomes back. It is the
// push replacement for the GET /api/commands short-poll (issue #477). The
// channel authenticates once at connect via the host bearer token in
// connection metadata; there is no per-frame credential.

package control

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	ControlChannel_Connect_FullMethodName = "/fleetedr.control.v1.ControlChannel/Connect"
)

// ControlChannelClient is the client API for ControlChannel service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// ControlChannel is the gateway service. The gateway is an explicitly
// sanctioned stateful tier (ADR-0010 amendment): it holds live connections
// and per-connection bookkeeping only, and persists nothing durable.
type ControlChannelClient interface {
	// Connect opens the persistent control stream for one host. The host
	// authenticates once, at connect, with its signed bearer token presented in
	// the gRPC metadata key "authorization" as "Bearer <token>". The server
	// pushes ServerFrames (commands) down the stream and reads AgentFrames
	// (outcomes) up the stream until either side closes.
	Connect(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[AgentFrame, ServerFrame], error)
}

type controlChannelClient struct {
	cc grpc.ClientConnInterface
}

func NewControlChannelClient(cc grpc.ClientConnInterface) ControlChannelClient {
	return &controlChannelClient{cc}
}

func (c *controlChannelClient) Connect(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[AgentFrame, ServerFrame], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &ControlChannel_ServiceDesc.Streams[0], ControlChannel_Connect_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[AgentFrame, ServerFrame]{ClientStream: stream}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type ControlChannel_ConnectClient = grpc.BidiStreamingClient[AgentFrame, ServerFrame]

// ControlChannelServer is the server API for ControlChannel service.
// All implementations must embed UnimplementedControlChannelServer
// for forward compatibility.
//
// ControlChannel is the gateway service. The gateway is an explicitly
// sanctioned stateful tier (ADR-0010 amendment): it holds live connections
// and per-connection bookkeeping only, and persists nothing durable.
type ControlChannelServer interface {
	// Connect opens the persistent control stream for one host. The host
	// authenticates once, at connect, with its signed bearer token presented in
	// the gRPC metadata key "authorization" as "Bearer <token>". The server
	// pushes ServerFrames (commands) down the stream and reads AgentFrames
	// (outcomes) up the stream until either side closes.
	Connect(grpc.BidiStreamingServer[AgentFrame, ServerFrame]) error
	mustEmbedUnimplementedControlChannelServer()
}

// UnimplementedControlChannelServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedControlChannelServer struct{}

func (UnimplementedControlChannelServer) Connect(grpc.BidiStreamingServer[AgentFrame, ServerFrame]) error {
	return status.Errorf(codes.Unimplemented, "method Connect not implemented")
}
func (UnimplementedControlChannelServer) mustEmbedUnimplementedControlChannelServer() {}
func (UnimplementedControlChannelServer) testEmbeddedByValue()                        {}

// UnsafeControlChannelServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ControlChannelServer will
// result in compilation errors.
type UnsafeControlChannelServer interface {
	mustEmbedUnimplementedControlChannelServer()
}

func RegisterControlChannelServer(s grpc.ServiceRegistrar, srv ControlChannelServer) {
	// If the following call pancis, it indicates UnimplementedControlChannelServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&ControlChannel_ServiceDesc, srv)
}

func _ControlChannel_Connect_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(ControlChannelServer).Connect(&grpc.GenericServerStream[AgentFrame, ServerFrame]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type ControlChannel_ConnectServer = grpc.BidiStreamingServer[AgentFrame, ServerFrame]

// ControlChannel_ServiceDesc is the grpc.ServiceDesc for ControlChannel service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var ControlChannel_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "fleetedr.control.v1.ControlChannel",
	HandlerType: (*ControlChannelServer)(nil),
	Methods:     []grpc.MethodDesc{},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "Connect",
			Handler:       _ControlChannel_Connect_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
	},
	Metadata: "internal/control/control.proto",
}
