// Skips covers the four skip branches of shouldSkipGroup:
//
//   - blocks below min-block (2 lines) are silently ignored.
//   - blocks whose first line is //go:* build / generate / embed directives skip.
//   - blocks starting with "// Code generated" skip.
//   - godoc paragraph-style blocks (those containing a blank // separator) skip.
package skips

//go:generate stringer -type=foo
//go:generate stringer -type=bar
//go:generate stringer -type=baz
var BuildDirectives = 1

// Code generated by something; DO NOT EDIT.
// short
// short
var GeneratedBanner = 1

// Summary line.
//
// Long paragraph below the blank godoc separator means the block reads as
// paragraph-style prose and the analyzer leaves it alone, even though the
// summary line is short.
var GodocParagraph = 1

// only two
// lines here
var TooShort = 1
