package main

import (
	"bytes"
	"os"
	"path/filepath"
	"testing"

	"github.com/stretchr/testify/require"
)

func TestScanComments(t *testing.T) {
	cases := []struct {
		name     string
		source   string
		cfg      config
		wantHits int
		// wantOut is a substring that must appear in the offender output when wantHits > 0. Kept short to avoid coupling
		// tests to formatting churn. Empty means "no substring assertion required for this case."
		wantOut string
	}{
		{
			name: "block with at least one line near target does not fire",
			// The first line clears 100 chars, so the block's longest line is well past the (width - 20) threshold. The other
			// lines being shorter is fine: humans wrap mid-paragraph for grammar, not for the wrap target.
			source: `package x

// This is a comment line filling up to roughly one hundred and fifteen characters before naturally wrapping here
// shorter follow-up line
// and another short one rounding out the block
var X = 1
`,
			cfg:      config{width: 120, minBlock: 3},
			wantHits: 0,
		},
		{
			name: "block where every line is short fires once per block",
			source: `package x

// Lorem ipsum dolor sit amet
// consectetur adipiscing elit
// Mauris ut imperdiet diam
var X = 1
`,
			cfg:      config{width: 120, minBlock: 3},
			wantHits: 1,
			wantOut:  "comment block of 3 lines wrapped narrowly",
		},
		{
			name: "two-line block is below min-block threshold",
			source: `package x

// short one
// short two
var X = 1
`,
			cfg:      config{width: 120, minBlock: 3},
			wantHits: 0,
		},
		{
			name: "build directives skip even when narrow",
			source: `package x

//go:build !windows
//go:generate stringer -type=Pill
//go:embed dist/*
var X = 1
`,
			cfg:      config{width: 120, minBlock: 3},
			wantHits: 0,
		},
		{
			name: "generated code banner is skipped",
			source: `package x

// Code generated by foo; DO NOT EDIT.
// source: foo.proto
// some other note
var X = 1
`,
			cfg:      config{width: 120, minBlock: 3},
			wantHits: 0,
		},
		{
			name: "block /* */ comment is ignored even when narrow",
			source: `package x

/*
short one
short two
short three
*/
var X = 1
`,
			cfg:      config{width: 120, minBlock: 3},
			wantHits: 0,
		},
		{
			name: "godoc paragraph (contains blank // separator) is skipped",
			// The blank `//` is the standard godoc paragraph separator. Treat the whole group as deliberate
			// paragraph-formatted prose and skip even when the summary line is short.
			source: `package x

// Foo does X.
//
// It also does Y in a manner consistent with established practice.
var X = 1
`,
			cfg:      config{width: 120, minBlock: 3},
			wantHits: 0,
		},
		{
			name: "min-block of 2 lets a two-line narrow block fire",
			source: `package x

// Lorem ipsum dolor sit amet
// consectetur adipiscing elit
var X = 1
`,
			cfg:      config{width: 120, minBlock: 2},
			wantHits: 1,
		},
		{
			name: "narrower width threshold suppresses hits that the default flagged",
			// Same content as the narrow-block case, but with width=40 the (width - 20) threshold drops to 20, which the
			// 28-30 char lines already clear. Confirms width configurability scales as expected.
			source: `package x

// Lorem ipsum dolor sit amet
// consectetur adipiscing elit
// Mauris ut imperdiet diam
var X = 1
`,
			cfg:      config{width: 40, minBlock: 3},
			wantHits: 0,
		},
	}

	for _, tc := range cases {
		t.Run(tc.name, func(t *testing.T) {
			t.Helper()
			dir := t.TempDir()
			path := filepath.Join(dir, "x.go")
			require.NoError(t, os.WriteFile(path, []byte(tc.source), 0o600))

			var buf bytes.Buffer
			hits, err := scanFile(&buf, path, tc.cfg)
			require.NoError(t, err)
			require.Equal(t, tc.wantHits, hits, "output was:\n%s", buf.String())
			if tc.wantOut != "" {
				require.Contains(t, buf.String(), tc.wantOut)
			}
		})
	}
}

func TestConfigMinLineLen(t *testing.T) {
	require.Equal(t, 100, config{width: 120}.minLineLen())
	require.Equal(t, 120, config{width: 140}.minLineLen())
	require.Equal(t, 60, config{width: 80}.minLineLen())
	// Floor at 1 when width is impossibly small, so the threshold never goes non-positive (which would make every
	// block "narrow").
	require.Equal(t, 1, config{width: 10}.minLineLen())
	require.Equal(t, 1, config{width: 0}.minLineLen())
}

func TestSkipDir(t *testing.T) {
	for _, name := range []string{"vendor", "node_modules", ".git", "tmp", "ai", "dist", "build", "DerivedData"} {
		require.True(t, skipDir(name), "%q should be skipped", name)
	}
	for _, name := range []string{"server", "agent", "internal", "test", "tools"} {
		require.False(t, skipDir(name), "%q should be walked", name)
	}
}

func TestWalkRecursesAndCounts(t *testing.T) {
	dir := t.TempDir()
	require.NoError(t, os.MkdirAll(filepath.Join(dir, "sub", "deeper"), 0o750))

	narrow := `package x

// short one
// short two
// short three
var X = 1
`
	require.NoError(t, os.WriteFile(filepath.Join(dir, "a.go"), []byte(narrow), 0o600))
	require.NoError(t, os.WriteFile(filepath.Join(dir, "sub", "b.go"), []byte(narrow), 0o600))
	require.NoError(t, os.WriteFile(filepath.Join(dir, "sub", "deeper", "c.go"), []byte(narrow), 0o600))
	// vendor/ subtree should not be walked, even with offending files inside.
	require.NoError(t, os.MkdirAll(filepath.Join(dir, "vendor"), 0o750))
	require.NoError(t, os.WriteFile(filepath.Join(dir, "vendor", "skip.go"), []byte(narrow), 0o600))

	var stdout, stderr bytes.Buffer
	hits := walk(&stdout, &stderr, []string{dir}, config{width: 120, minBlock: 3})
	require.Equal(t, 3, hits, "three offender files, one entry per file/block; vendor must be skipped\n%s", stdout.String())
	require.NotContains(t, stdout.String(), "vendor/skip.go")
}

func TestWalkUsesPathInOutput(t *testing.T) {
	dir := t.TempDir()
	path := filepath.Join(dir, "x.go")
	require.NoError(t, os.WriteFile(path, []byte(`package x

// short
// short
// short
var X = 1
`), 0o600))

	var stdout, stderr bytes.Buffer
	_ = walk(&stdout, &stderr, []string{dir}, config{width: 120, minBlock: 3})
	require.Contains(t, stdout.String(), path, "offender lines must cite the file path")
	require.Empty(t, stderr.String(), "no errors expected for a clean walk")
}
