package main

import (
	"os"
	"path/filepath"
	"strings"
	"testing"

	"github.com/stretchr/testify/assert"
	"github.com/stretchr/testify/require"
)

// Drift assertions (the committed pack matching the registered detections) live in server/rules/bootstrap, not here: CI runs
// ./server/... but not ./tools/..., so a drift check in this package would never gate a build. What remains here is the
// generator's own behaviour: what it writes, how it names files, what it prunes, and how it fails.

// TestGenerateWritesThePack drives the writer end to end against a temp directory, so the file naming and the header prepend are
// covered rather than only the rendering underneath them.
func TestGenerateWritesThePack(t *testing.T) {
	t.Parallel()

	dir := t.TempDir()
	n, err := generate(dir)
	require.NoError(t, err)
	assert.Positive(t, n)

	entries, err := os.ReadDir(dir)
	require.NoError(t, err)
	assert.Len(t, entries, n, "one file per rendered rule")

	body, err := os.ReadFile(filepath.Join(dir, "credential_keychain_dump.yml")) //nolint:gosec // temp dir under test control
	require.NoError(t, err)
	assert.True(t, strings.HasPrefix(string(body), "# Generated by tools/gen-rule-pack"))
	assert.Contains(t, string(body), "title: Keychain credential dump")
}

// TestGenerateRejectsAnUnwritableDestination covers the error path, so a failure to write is surfaced rather than reported as a
// successful run that produced nothing.
func TestGenerateRejectsAnUnwritableDestination(t *testing.T) {
	t.Parallel()

	// A path whose parent is a regular file cannot be created as a directory.
	blocker := filepath.Join(t.TempDir(), "not-a-dir")
	require.NoError(t, os.WriteFile(blocker, []byte("x"), 0o600))

	_, err := generate(filepath.Join(blocker, "pack"))
	require.Error(t, err)
}

// TestGeneratePrunesObsoleteFiles covers the deletion path. Without pruning, removing or renaming a detection leaves its file
// behind, the drift check fails on the extra file, and the failure message tells the developer to run the very command that will
// not remove it.
func TestGeneratePrunesObsoleteFiles(t *testing.T) {
	t.Parallel()

	dir := t.TempDir()
	stale := filepath.Join(dir, "deleted_rule.yml")
	readme := filepath.Join(dir, "README.md")
	require.NoError(t, os.WriteFile(stale, []byte("stale"), 0o600))
	require.NoError(t, os.WriteFile(readme, []byte("# keep me"), 0o600))

	_, err := generate(dir)
	require.NoError(t, err)

	assert.NoFileExists(t, stale, "a file for an unregistered rule must be removed")
	assert.FileExists(t, readme, "non-YAML files in the pack directory must survive regeneration")
}
