package main

import (
	"strings"
	"testing"

	"github.com/stretchr/testify/assert"
	"github.com/stretchr/testify/require"
)

// fixtureBundle is a miniature STIX bundle carrying every shape the extractor has to get right: a matrix whose tactic order is
// deliberately NOT alphabetical, a revoked technique, a deprecated one, a multi-tactic technique, and techniques declared out
// of id order.
func fixtureBundle() stixBundle {
	tactic := func(id, short, name string) stixObject {
		return stixObject{Type: "x-mitre-tactic", ID: id, Shortname: short, Name: name}
	}
	technique := func(extID, name string, phases []string, revoked, deprecated bool) stixObject {
		kc := make([]killChainPhase, 0, len(phases))
		for _, p := range phases {
			kc = append(kc, killChainPhase{KillChainName: "mitre-attack", PhaseName: p})
		}
		return stixObject{
			Type: "attack-pattern", Name: name, Revoked: revoked, Deprecated: deprecated,
			KillChainPhases:   kc,
			ExternalReference: []externalReference{{SourceName: "mitre-attack", ExternalID: extID}},
		}
	}
	return stixBundle{Objects: []stixObject{
		{Type: "x-mitre-collection", Version: "19.2"},
		tactic("tac--exec", "execution", "Execution"),
		tactic("tac--persist", "persistence", "Persistence"),
		tactic("tac--privesc", "privilege-escalation", "Privilege Escalation"),
		// Matrix order is Execution, Persistence, Privilege Escalation. Alphabetical would put Execution first too, so the
		// refs are listed with Persistence before Execution to prove the ORDER is read rather than sorted.
		{Type: "x-mitre-matrix", ID: "matrix--1", TacticRefs: []string{"tac--persist", "tac--exec", "tac--privesc"}},
		technique("T2000", "Later Id", []string{"execution"}, false, false),
		technique("T1000", "Earlier Id", []string{"execution"}, false, false),
		technique("T1500", "Multi Tactic", []string{"persistence", "privilege-escalation"}, false, false),
		technique("T9998", "Withdrawn", []string{"execution"}, true, false),
		technique("T9999", "Retired", []string{"execution"}, false, true),
	}}
}

func TestExtract(t *testing.T) {
	t.Parallel()
	version, tactics, techniques, err := extract(fixtureBundle())
	require.NoError(t, err)

	assert.Equal(t, "19.2", version)

	// Matrix order, not sorted. Sorting would put Execution first and misrepresent every ATT&CK rendering.
	var order []string
	for _, tc := range tactics {
		order = append(order, tc.Display)
	}
	assert.Equal(t, []string{"Persistence", "Execution", "Privilege Escalation"}, order)

	var ids []string
	for _, tech := range techniques {
		ids = append(ids, tech.ID)
	}
	// Sorted by id so a regeneration diff shows only real ATT&CK changes, and the revoked and deprecated ones are gone: a
	// table naming a withdrawn technique would send an operator to a page ATT&CK no longer publishes.
	assert.Equal(t, []string{"T1000", "T1500", "T2000"}, ids)

	assert.Equal(t, []string{"persistence", "privilege-escalation"}, techniques[1].Tactics,
		"a technique keeps every tactic ATT&CK gives it, in ATT&CK's order")
}

func TestExtract_RejectsAnIncompleteBundle(t *testing.T) {
	t.Parallel()
	cases := []struct {
		name    string
		mutate  func(*stixBundle)
		wantErr string
	}{
		{"no collection version", func(b *stixBundle) { b.Objects[0].Type = "x-mitre-other" }, "version"},
		{"no matrix", func(b *stixBundle) {
			for i := range b.Objects {
				if b.Objects[i].Type == "x-mitre-matrix" {
					b.Objects[i].Type = "x-mitre-other"
				}
			}
		}, "matrix"},
		{"no techniques", func(b *stixBundle) {
			for i := range b.Objects {
				if b.Objects[i].Type == "attack-pattern" {
					b.Objects[i].Revoked = true
				}
			}
		}, "techniques"},
	}
	for _, tc := range cases {
		t.Run(tc.name, func(t *testing.T) {
			t.Parallel()
			b := fixtureBundle()
			tc.mutate(&b)
			_, _, _, err := extract(b)
			require.Error(t, err, "an unusable bundle must fail loudly rather than generate a thin table")
			assert.Contains(t, err.Error(), tc.wantErr)
		})
	}
}

func TestRender(t *testing.T) {
	t.Parallel()
	version, tactics, techniques, err := extract(fixtureBundle())
	require.NoError(t, err)
	out := render(version, tactics, techniques)

	assert.Contains(t, out, "Code generated by tools/attacktable. DO NOT EDIT.")
	// The ATT&CK Terms of Use permit redistribution on the condition that MITRE's copyright designation travels with it, so
	// the attribution is part of the artifact, not a nicety.
	assert.Contains(t, out, attribution)
	assert.Contains(t, out, `export const ATTACK_VERSION = "19.2";`)
	// Tactic display names, resolved from the shortnames the techniques carry.
	assert.Contains(t, out, `"T1500": { id: "T1500", name: "Multi Tactic", tactic: "Persistence", `+
		`tactics: ["Persistence", "Privilege Escalation"] },`)

	// Byte-identical across runs, so a regeneration diff is readable and an unchanged release produces no diff at all.
	assert.Equal(t, out, render(version, tactics, techniques))
	assert.Less(t, strings.Index(out, `"T1000"`), strings.Index(out, `"T2000"`), "rows are emitted in id order")
}
