//go:build windows

package hostid

import (
	"context"
	"fmt"
	"strings"

	"golang.org/x/sys/windows/registry"
)

// readMachineGUID reads HKLM\SOFTWARE\Microsoft\Cryptography\MachineGuid. Declared as a var so tests can substitute a fake without a real
// registry. The real reader opens the key read-only and returns the string value.
var readMachineGUID = func() (string, error) {
	key, err := registry.OpenKey(registry.LOCAL_MACHINE, `SOFTWARE\Microsoft\Cryptography`, registry.QUERY_VALUE|registry.WOW64_64KEY)
	if err != nil {
		return "", fmt.Errorf("open Cryptography key: %w", err)
	}
	defer func() { _ = key.Close() }()
	guid, _, err := key.GetStringValue("MachineGuid")
	if err != nil {
		return "", fmt.Errorf("read MachineGuid: %w", err)
	}
	return guid, nil
}

// Get returns the Windows machine identifier: the registry MachineGuid under HKLM\SOFTWARE\Microsoft\Cryptography. MachineGuid is a
// per-OS-install GUID that is stable across reboots and OS updates, readable without administrator rights, and regenerated by
// sysprep /generalize, so cloned images do not collide, unlike the frequently duplicated SMBIOS UUID. The ctx is accepted for interface
// symmetry with the macOS Get (which shells out); the registry read is local and effectively instant, so it is not cancellable.
func Get(_ context.Context) (string, error) {
	guid, err := readMachineGUID()
	if err != nil {
		return "", err
	}
	guid = strings.TrimSpace(guid)
	if guid == "" {
		return "", fmt.Errorf("MachineGuid is empty")
	}
	return guid, nil
}
